package enderpower.Items;

import cpw.mods.fml.common.registry.GameRegistry;
import enderpower.lib.R;
import enderpower.main.Enderpower;
import enderpower.tools.BatAxe;
import enderpower.tools.ToolRegistratie;
import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.util.EnumHelper;

public class EnderpowerItems {
	

	public static Item thau_ball;
	public static Item sie_gem;
	public static Item dou_dust;
	public static Item gee_dust;
	public static Item thau_powder;
	public static Item sie_powder;
	public static Item dou_powder;
	public static Item gee_powder;
	public static Item energy_drainer;
	public static Item blood_stick;
	public static Item bat_eye;
	public static Item bat_tooth;
	public static Item magic_mixer;
	public static Item magic_stick;
	public static Item doustick;
	public static Item geestick;
	public static Item fiestick;
	public static Item glass_orb;
	public static Item batskin;
	public static Item blood;
	public static Item poisonedblood;
	public static Item urine;
	public static Item literbottle;
	public static Item fie_dust;
	public static Item fie_powder;
	public static Item enderdust;
	public static Item enderpowder;
	public static Item magicfuel;
	public static Item fiefuel;
	public static Item geefuel;
	public static Item doufuel;
	public static Item enderfuel;
	public static Item douorb;
	public static Item blastpowder;
	public static Item fieorb;
	public static Item compressedblastpowder;
	public static Item explosiveorb;
	public static Item manabooster;
	public static Item testitem2;
	public static Item witherpowder;
	public static Item witherdust;
	public static Item witherstick;
	public static Item cursedstick;
	public static Item cursedorb;
	public static Item endergem;
	public static Item enderstick;
	public static Item enderorb;
	public static Item cursedpowder;
	public static Item cursedmetal;
	public static Item itemmanameter;
	public static Item poison;
	public static Item speedessence;
	public static Item speedpowder;
	public static Item lightningstick;
	public static Item lightningorb;
	public static Item lightningpowder;
	public static Item testitem3;
	public static Item holypowder;
	public static Item holystick;
	public static Item holyorb;
	public static Item geeorb;
	public static Item magichandle;
	public static Item flyessence;
	public static Item flypowder;
	public static Item flystick;
	public static Item flyorb;
	public static Item speedorb;
	public static Item speedstick;
	public static Item thauorb;
	public static Item siefuel;
	
	
	
	
	public static void load() {
	thau_ball = new MagicItem().setUnlocalizedName(R.T + R.UNLOCALIZET_ITEM_THAUBALL).setTextureName(R.T + R.UNLOCALIZET_ITEM_THAUBALL);
	sie_gem = new MagicItem().setUnlocalizedName(R.T + R.UNLOCALIZET_ITEM_SIEGEM).setTextureName(R.T + R.UNLOCALIZET_ITEM_SIEGEM);
	thau_powder = new MagicItem().setUnlocalizedName(R.T + R.UNLOCALIZET_ITEM_THAUPOWDER).setTextureName(R.T + R.UNLOCALIZET_ITEM_THAUPOWDER);
	sie_powder = new MagicItem().setUnlocalizedName(R.T + R.UNLOCALIZET_ITEM_SIEPOWDER).setTextureName(R.T + R.UNLOCALIZET_ITEM_SIEPOWDER);
	dou_powder = new MagicItem().setUnlocalizedName(R.T + R.UNLOCALIZET_ITEM_DOUPOWDER).setTextureName(R.T + R.UNLOCALIZET_ITEM_DOUPOWDER);
	gee_powder = new MagicItem().setUnlocalizedName(R.T + R.UNLOCALIZET_ITEM_GEEPOWDER).setTextureName(R.T + R.UNLOCALIZET_ITEM_GEEPOWDER);
	dou_dust = new MagicItem().setUnlocalizedName(R.T + R.UNLOCALIZET_ITEM_DOUDUST).setTextureName(R.T + R.UNLOCALIZET_ITEM_DOUDUST);
	energy_drainer = new ItemGui().setUnlocalizedName(R.T + R.UNLOCALIZET_ITEM_ENERGYDRAINER).setTextureName(R.T + R.UNLOCALIZET_ITEM_ENERGYDRAINER);
	blood_stick = new MagicItem().setUnlocalizedName(R.T + R.UNLOCALIZET_ITEM_BLOODSTICK).setTextureName(R.T + R.UNLOCALIZET_ITEM_BLOODSTICK);
	gee_dust = new MagicItem().setUnlocalizedName(R.T + R.UNLOCALIZET_ITEM_GEEDUST).setTextureName(R.T + R.UNLOCALIZET_ITEM_GEEDUST);
	bat_eye = new StandaartItem().setUnlocalizedName(R.T + R.UNLOCALIZET_ITEM_BATEYE).setTextureName(R.T + R.UNLOCALIZET_ITEM_BATEYE);
	bat_tooth = new StandaartItem().setUnlocalizedName(R.T + R.UNLOCALIZET_ITEM_BATTOOTH).setTextureName(R.T + R.UNLOCALIZET_ITEM_BATTOOTH);
	magic_mixer = new ItemGui().setUnlocalizedName(R.T + R.UNLOCALIZET_ITEM_MAGICMIXER).setTextureName(R.T + "magic mixer");
	geestick = new MagicItem().setUnlocalizedName("geestick").setTextureName(R.T + "geestick");
	doustick = new MagicItem().setUnlocalizedName("doustick").setTextureName(R.T + "doustick");
	fiestick = new MagicItem().setUnlocalizedName("fiestick").setTextureName(R.T + "fiestick");
	magic_stick = new MagicItem().setUnlocalizedName("magic stick").setTextureName(R.T + "magic stick");
	glass_orb = new MagicItem().setUnlocalizedName("glass_orb").setTextureName(R.T + "glass_orb");
	batskin = new StandaartItem().setUnlocalizedName("bat skin").setTextureName(R.T + "bat skin");
	blood = new StandaartItem().setUnlocalizedName("blood").setTextureName(R.T + "blood");
	poisonedblood = new StandaartItem().setUnlocalizedName("poisonedblood").setTextureName(R.T + "poisonedblood");
	urine = new StandaartItem().setUnlocalizedName("urine").setTextureName(R.T + "urine");
	literbottle = new StandaartItem().setUnlocalizedName("literbottle").setTextureName(R.T + "emptyliterbottle");
	fie_dust = new MagicItem().setUnlocalizedName("fiedust").setTextureName(R.T + "fiedust");
	fie_powder = new MagicItem().setUnlocalizedName("fiepowder").setTextureName(R.T + "fiepowder");
	enderdust = new MagicItem().setUnlocalizedName("enderdust").setTextureName(R.T + "enderdust");
	enderpowder = new MagicItem().setUnlocalizedName("enderpowder").setTextureName(R.T + "enderpowder");
	magicfuel = new MagicItem().setUnlocalizedName("magicfuel").setTextureName(R.T + "magicfuel");
	geefuel = new MagicItem().setUnlocalizedName("geefuel").setTextureName(R.T + "geefuel");
	fiefuel = new MagicItem().setUnlocalizedName("fiefuel").setTextureName(R.T + "fiefuel");
	doufuel = new MagicItem().setUnlocalizedName("doufuel").setTextureName(R.T + "doufuel");
	enderfuel = new MagicItem().setUnlocalizedName("enderfuel").setTextureName(R.T + "enderfuel");
	douorb = new MagicItem().setUnlocalizedName("douorb").setTextureName(R.T + "douorb");
	blastpowder = new MagicItem().setUnlocalizedName("blastpowder").setTextureName(R.T + "blastpowder");
	compressedblastpowder = new MagicItem().setUnlocalizedName("compressedblastpowder").setTextureName(R.T + "compressedblastpowder");
	fieorb = new MagicItem().setUnlocalizedName("fieorb").setTextureName(R.T + "fieorb");
	explosiveorb = new MagicItem().setUnlocalizedName("explosiveorb").setTextureName(R.T + "explosiveorb");
	manabooster = new Testitem1().setUnlocalizedName("manabooster").setTextureName(R.T + "testitem1");
	testitem2 = new Testitem2().setUnlocalizedName("testitem2").setTextureName(R.T + "testitem1");
	witherdust = new MagicItem().setUnlocalizedName("witherdust").setTextureName(R.T + "witherdust");
	witherpowder = new MagicItem().setUnlocalizedName("witherpowder").setTextureName(R.T + "witherpowder");
	witherstick = new MagicItem().setUnlocalizedName("witherstick").setTextureName(R.T + "witherstick");
	cursedstick = new MagicItem().setUnlocalizedName("cursedstick").setTextureName(R.T + "cursedstick");
	cursedorb = new MagicItem().setUnlocalizedName("cursedorb").setTextureName(R.T + "cursedorb");
	endergem = new MagicItem().setUnlocalizedName("endergem").setTextureName(R.T + "endergem");
	enderstick = new MagicItem().setUnlocalizedName("enderstick").setTextureName(R.T + "enderstick");
	enderorb = new MagicItem().setUnlocalizedName("enderorb").setTextureName(R.T + "enderorb");
	cursedpowder = new MagicItem().setUnlocalizedName("cursedpowder").setTextureName(R.T + "cursedpowder");
	cursedmetal = new MagicItem().setUnlocalizedName("cursedmetal").setTextureName(R.T + "cursedmetal");
	itemmanameter = new ManaMeterItem().setUnlocalizedName("itemmanameter").setTextureName(R.T + "itemmanameter");
	poison = new Poison().setUnlocalizedName("poison").setTextureName(R.T + "poison");
	speedessence = new MagicItem().setUnlocalizedName("speedessence").setTextureName(R.T + "speedessence");
	speedpowder = new MagicItem().setUnlocalizedName("speedpowder").setTextureName(R.T + "speedpowder");
	lightningstick = new MagicItem().setUnlocalizedName("lightningstick").setTextureName(R.T + "lightningstick");
	lightningpowder = new MagicItem().setUnlocalizedName("lightningpowder").setTextureName(R.T + "lightningpowder");
	lightningorb = new MagicItem().setUnlocalizedName("lightningorb").setTextureName(R.T + "lightningorb");
	testitem3 = new Testitem3().setUnlocalizedName("testitem3").setTextureName(R.T + "testitem1").setCreativeTab(CreativeTabs.tabMisc);
	holypowder = new MagicItem().setUnlocalizedName("holypowder").setTextureName(R.T + "holypowder");
	holystick = new MagicItem().setUnlocalizedName("holystick").setTextureName(R.T + "holystick");
	holyorb = new MagicItem().setUnlocalizedName("holyorb").setTextureName(R.T + "holyorb");
	geeorb = new MagicItem().setUnlocalizedName("geeorb").setTextureName(R.T + "geeorb");
	magichandle = new MagicItem().setUnlocalizedName("magichandle").setTextureName(R.T + "magichandle");
	flyessence = new MagicItem().setUnlocalizedName("flyessence").setTextureName(R.T + "flyessence");
	flypowder = new MagicItem().setUnlocalizedName("flypowder").setTextureName(R.T + "flypowder");
	flystick = new MagicItem().setUnlocalizedName("flystick").setTextureName(R.T + "flystick");
	flyorb = new MagicItem().setUnlocalizedName("flyorb").setTextureName(R.T + "flyorb");
	speedstick = new MagicItem().setUnlocalizedName("speedstick").setTextureName(R.T + "speedstick");
	speedorb = new MagicItem().setUnlocalizedName("speedorb").setTextureName(R.T + "speedorb");
	thauorb = new MagicItem().setUnlocalizedName("thauorb").setTextureName(R.T + "thauorb");
	siefuel = new MagicItem().setUnlocalizedName("siefuel").setTextureName(R.T + "siefuel");
	
	
	}

	public static void RegisterItems() {
		GameRegistry.registerItem(thau_ball, R.UNLOCALIZET_ITEM_THAUBALL);
		GameRegistry.registerItem(sie_gem, R.UNLOCALIZET_ITEM_SIEGEM);
		GameRegistry.registerItem(dou_dust, R.UNLOCALIZET_ITEM_DOUDUST);
		GameRegistry.registerItem(gee_dust, R.UNLOCALIZET_ITEM_GEEDUST);
		GameRegistry.registerItem(thau_powder, R.UNLOCALIZET_ITEM_THAUPOWDER);
		GameRegistry.registerItem(sie_powder, R.UNLOCALIZET_ITEM_SIEPOWDER);
		GameRegistry.registerItem(dou_powder, R.UNLOCALIZET_ITEM_DOUPOWDER);
		GameRegistry.registerItem(gee_powder, R.UNLOCALIZET_ITEM_GEEPOWDER);
		GameRegistry.registerItem(energy_drainer, R.UNLOCALIZET_ITEM_ENERGYDRAINER);
		GameRegistry.registerItem(blood_stick, R.UNLOCALIZET_ITEM_BLOODSTICK);
		GameRegistry.registerItem(bat_eye, R.UNLOCALIZET_ITEM_BATEYE);
		GameRegistry.registerItem(bat_tooth, R.UNLOCALIZET_ITEM_BATTOOTH);
		GameRegistry.registerItem(magic_mixer, R.UNLOCALIZET_ITEM_MAGICMIXER);
		GameRegistry.registerItem(magic_stick, "magic_stick");
		GameRegistry.registerItem(geestick, "geestick");
		GameRegistry.registerItem(fiestick, "fiestick");
		GameRegistry.registerItem(doustick, "doustick");
		GameRegistry.registerItem(glass_orb, "glass_orb");
		GameRegistry.registerItem(batskin, "bat_skin");
		GameRegistry.registerItem(blood, "blood");
		GameRegistry.registerItem(poisonedblood, "poisonedblood");
		GameRegistry.registerItem(urine, "urine");
		GameRegistry.registerItem(literbottle, "literbottle");
		GameRegistry.registerItem(fie_dust, "fiedust");
		GameRegistry.registerItem(fie_powder, "fiepowder");
		GameRegistry.registerItem(enderdust, "enderdust");
		GameRegistry.registerItem(enderpowder, "enderpowder");
		GameRegistry.registerItem(manabooster, "manabooster");
		GameRegistry.registerItem(testitem2, "testitem2");
		GameRegistry.registerItem(magicfuel, "magicfuel");
		GameRegistry.registerItem(fiefuel, "fiefuel");
		GameRegistry.registerItem(geefuel, "geefuel");
		GameRegistry.registerItem(doufuel, "doufuel");
		GameRegistry.registerItem(enderfuel, "enderfuel");
		GameRegistry.registerItem(douorb, "douorb");
		GameRegistry.registerItem(blastpowder, "blastpowder");
		GameRegistry.registerItem(fieorb, "fieorb");
		GameRegistry.registerItem(compressedblastpowder, "compressedblastpowder");
		GameRegistry.registerItem(explosiveorb, "explosiveorb");
		GameRegistry.registerItem(witherdust, "witherdust");
		GameRegistry.registerItem(witherpowder, "witherpowder");
		GameRegistry.registerItem(witherstick, "witherstick");
		GameRegistry.registerItem(cursedstick, "cursedstick");
		GameRegistry.registerItem(cursedorb, "cursedorb");
		GameRegistry.registerItem(endergem, "endergem");
		GameRegistry.registerItem(enderstick, "enderstick");
		GameRegistry.registerItem(enderorb, "enderorb");
		GameRegistry.registerItem(cursedpowder, "cursedpowder");
		GameRegistry.registerItem(cursedmetal, "cursedmetal");
		GameRegistry.registerItem(itemmanameter, "itemmanameter");
		GameRegistry.registerItem(poison, "poison");
		GameRegistry.registerItem(speedessence, "speedessence");
		GameRegistry.registerItem(speedpowder, "speedpowder");
		GameRegistry.registerItem(lightningstick, "lightningstick");
		GameRegistry.registerItem(lightningpowder, "lightningpowder");
		GameRegistry.registerItem(lightningorb, "lightningorb");
		GameRegistry.registerItem(testitem3, "testitem3");
		GameRegistry.registerItem(holyorb, "holyorb");
		GameRegistry.registerItem(holypowder, "holypowder");
		GameRegistry.registerItem(holystick, "holystick");
		GameRegistry.registerItem(geeorb, "geeorb");
		GameRegistry.registerItem(magichandle, "magichandle");
		GameRegistry.registerItem(flyessence, "flyessence");
		GameRegistry.registerItem(flypowder, "flypowder");
		GameRegistry.registerItem(flystick, "flystick");
		GameRegistry.registerItem(flyorb, "flyorb");
		GameRegistry.registerItem(speedstick, "speedstick");
		GameRegistry.registerItem(speedorb, "speedorb");
		GameRegistry.registerItem(thauorb, "thauorb");
		GameRegistry.registerItem(siefuel, "siefuel");

		
	}

}
